version: "3.4"

services:
  redpanda:
      command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      image: docker.vectorized.io/vectorized/redpanda:latest
      container_name: redpanda-1
      ports:
      - 9092:9092
      - 29092:29092

  server:
    image: ghcr.io/deephaven/server:${VERSION:-0.14.0}
    environment:
      JAVA_TOOL_OPTIONS: -Xmx6g -Ddeephaven.console.type=python -Ddeephaven.application.dir=/data/app.d
    depends_on:
        - redpanda
    expose:
      - '8080'
    volumes:
      - ./data:/data
      - api-cache:/cache

  web:
    image: ghcr.io/deephaven/web:${VERSION:-latest}
    environment:
      JAVA_TOOL_OPTIONS: -Xmx4g
    expose:
      - '80'
    volumes:
      - ./data:/data
      - web-tmp:/tmp

  grpc-proxy:
    image: ghcr.io/deephaven/grpc-proxy:${VERSION:-latest}
    environment:
      - BACKEND_ADDR=server:8080
    depends_on:
      - server
    expose:
      - '8080'

  envoy:
    image: ghcr.io/deephaven/envoy:${VERSION:-latest}
    depends_on:
      - web
      - grpc-proxy
      - server
    ports:
      - "${PORT:-10000}:10000"

volumes:
    web-tmp:
    api-cache:
